version: '3.8'
services:
  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=none
    ports:
      - '7687:7687'
  backend:
    build: ./web/backend
    command: python App.py
    volumes:
      - .:/backSrc
    ports:
      - '8080:8080'
    depends_on:
      - neo4j
  frontend:
    build: ./web/frontend
    command: npm start
    expose:
      - 3000
    ports:
      - '3000:3000'
    depends_on:
      - backend
    hostname: localhost
